### ISSUE TITLE
Unable to run gui.py on more recent matplotlib

### ISSUE THREAD

**Issue by 3x10e8** [lukaribar/circuit-neuromodulation#7]
I am using Python 3.9.12 and with matplotlib 3.6.1 and trying to run the gui. Initially I would get the "IMPORTANT: Resizing figure is not supported" error from line #80. Then I realized that my backend was set to MacOSX, so I installed PyQt5, and then tried switching matplotlib's backend by adding the following to the top of gui_utilities.py:
```
import sys
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
```
This doesn't error right away but I can't see a visible GUI...
Trying to deprecate matplotlib now based on requirements.txt, but is there an easier way to run the gui on updated matplotlib?

**Comment by 3x10e8** [comment]
Update: created a virtual environment in conda with 
```
python=3.6 numpy=1.14.0 scipy=1.0.0 matplotlib=2.1.2
```
The backend now matches the [expected](https://github.com/lukaribar/Circuit-Neuromodulation/blob/master/gui_utilities.py#L71) Qt5Agg, and the code appears to execute, but no GUI window is seen. This is with X-forwarding from a remote linux machine so that could be a part of the issue.

**Comment by lukaribar** [comment]
Hi, thanks for pointing this out! I will look into it as soon as I find some time - there were some issues with this before as well, and I was only testing on my machine at the time running Windows.

**Comment by lukaribar** [comment]
The issue seemed to stem from a missing `plt.show(block=False)` line that is required to render the initial figure and allow the interactive updates afterwards. I have updated the code to set the default backend to `Qt5Agg` as the default `MacOSX` on Mac systems was still not behaving as expected. The `requirements.txt` was updated to reflect this additional requirement.
